name: Linting

on:
  workflow_call:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect File Changes
        uses: dorny/paths-filter@v2
        id: changed-files
        with:
          list-files: shell
          filters: |
            linting:
              - added|modified: 'public/**/*.{pcss,json,js}'
              - added|modified: 'admin/**/*.{pcss,json,js}'
              - added|modified: '*.{json,js}'

      - name: Set up node
        if: steps.changed-files.outputs.linting == 'true'
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm dependencies
        if: steps.changed-files.outputs.linting == 'true'
        run: npm ci

      - name: Check linting
        if: steps.changed-files.outputs.linting == 'true'
        run: npm run server-lint
