name: Coding Standards

on:
  workflow_call:
    secrets:
      COMPOSER_ENV:
        required: true
        description: COMPOSER_ENV Secret

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect File Changes
        uses: dorny/paths-filter@v2
        id: changed-files
        with:
          list-files: shell
          filters: |
            phpcs:
              - added|modified: '*.php'
              - added|modified: 'phpcs.xml.dist'

      - name: Configure PHP environment
        if: steps.changed-files.outputs.phpcs == 'true'
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:2
          php-version: '8.0'

      - name: Get Composer Cache Directory
        id: composer-cache
        if: steps.changed-files.outputs.phpcs == 'true'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        if: steps.changed-files.outputs.phpcs == 'true'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer
        if: steps.changed-files.outputs.phpcs == 'true'
        run: |
          echo "${{ secrets.COMPOSER_ENV }}" >> .env
          composer install --ignore-platform-reqs --optimize-autoloader --no-progress
          rm .env

      - name: Run PHPCS
        if: steps.changed-files.outputs.phpcs == 'true'
        run: |
          composer phpcs
