name: 'Workflows'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  coding-standards:
    name: 'Coding Standards'
    uses: ./.github/workflows/phpcs.yml
    secrets:
      COMPOSER_ENV: ${{ secrets.COMPOSER_ENV }}

  phpstan:
    name: 'Static Analysis'
    needs: [coding-standards]
    uses: ./.github/workflows/static-analysis.yml
    secrets:
      COMPOSER_ENV: ${{ secrets.COMPOSER_ENV }}
